[project]
name = "changelog-helper"
version = "0.0.1"
dependencies = [
    "Jinja2",
]

[project.scripts]
changelog = "src.main:main"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-data]
src = [".j2", "templates/*.j2"]
